# -*- coding: utf-8 -*-
"""Streamlit_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Ftq-Rem--nmcBnUB_4CXHlNBsn3X36J
"""

import streamlit as st
import openai
import os

"""Hide your open AI platform key in an environment variable"""

# Commented out IPython magic to ensure Python compatibility.
# %env OPENAI_API_KEY=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

"""Import relevant libraries"""

def generate_code(input_string):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=input_string +"\n",
        max_tokens=1024,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        temperature=0.0,
        stop=None,
    )
    answer = response.choices[0].text.strip()
    return answer.replace('\n', ' ')

instructions = ['1. code to sort an array using selection sort algorithm',
                '2. code to generate the Fibonacci sequence',
                '3. code to checks whether a given number is prie or not',]

task = st.selectbox('Select a task to generate code for:', instructions)

input_string = "Generate C++ code for the following tasks:\n" + task
output = generate_code(input_string)

st.code(output, language='cpp')

if __name__ == '__main__':
    st.title('C++ Tutorial App')
    st.subheader('Generate code for basic programming tasks')
    task = st.selectbox('Select a task to generate code for:', instructions)
    input_string = "Generate C++ code for the following tasks:\n" + task
    output = generate_code(input_string)
    st.code(output, language='cpp')